# Generated by Django 4.1 on 2022-10-08 08:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300, verbose_name='Task')),
                ('priority_level', models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=20, verbose_name='Priority Levels')),
                ('status', models.BooleanField(choices=[('COMPLETED', 'COMPLETED'), ('ONGOING', 'ONGOING'), ('PENDING', 'PENDING')], default='PENDING', verbose_name='Task Status')),
                ('estimated_time', models.TimeField(verbose_name='Estimated Time')),
                ('task_complete_time', models.TimeField(default='00:00', verbose_name='Time for complete the task')),
                ('start_date_of_task', models.DateTimeField(verbose_name='Task start date and time')),
                ('end_date_of_task', models.DateTimeField(verbose_name='Task end date and time')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 10, 8, 8, 2, 51, 243997, tzinfo=datetime.timezone.utc), verbose_name='Task created date and time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User to created task')),
            ],
        ),
    ]
