# Generated by Django 4.1 on 2022-10-08 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotaskmodel',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 9, 59, 58, 356621, tzinfo=datetime.timezone.utc), verbose_name='Task created date and time'),
        ),
        migrations.AlterField(
            model_name='todotaskmodel',
            name='priority_level',
            field=models.CharField(choices=[('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('HIGH', 'HIGH')], max_length=20, verbose_name='Priority Levels'),
        ),
        migrations.AlterField(
            model_name='todotaskmodel',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('ONGOING', 'ONGOING')], default='PENDING', max_length=20, verbose_name='Task Status'),
        ),
    ]
